### ISSUE TITLE
About page completely blank

### ISSUE THREAD

**Issue by rmklaus12** [rmklaus12/all-about-git#11]
We have an 'about' page, but it is completely blank, not even our template. Not great. Need at least the template and maybe some dummy text for now?

**Comment by sulabhbartaula** [comment]
i will work on this

**Comment by Navneet-cmd** [comment]
Hi, may i contribute towards this.

**Comment by Rishitha-Mannemala** [comment]
Hey Robin, can I contribute a few to your about page.

**Comment by Rishitha-Mannemala** [comment]
Hi Robin can I contribute a little to your the about page
