### ISSUE TITLE
Create page for Contributors list

### ISSUE THREAD

**Issue by rmklaus12** [rmklaus12/all-about-git#2]
Create a page from page template, and add a form for Contributors to add their name, a link, short bio, maybe a picture?

**Comment by VarshaVBapat** [comment]
Hi Robin, Please assign this issue to me

**Comment by VarshaVBapat** [comment]
Thanks Robin ! but I am unable to push , as I get the following error : 
********************************************************
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
********************************************************

**Comment by lvemavarapu** [comment]
Hi Robin,
I am getting the following error:
remote: Permission to rmklaus12/all-about-git.git denied to lvemavarapu.
fatal: unable to access 'https://github.com/rmklaus12/all-about-git.git/': The requested URL returned error: 403

**Comment by rmklaus12** [comment]
> Thanks Robin ! but I am unable to push , as I get the following error :
> 
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.

I'm guessing by your PR, you resolved this, yes?

**Comment by rmklaus12** [comment]
> Hi Robin,
> I am getting the following error:
> remote: Permission to rmklaus12/all-about-git.git denied to lvemavarapu.
> fatal: unable to access 'https://github.com/rmklaus12/all-about-git.git/': The requested URL returned error: 403

What command did you use?
