### ISSUE TITLE
Too many contributor pages 

### ISSUE THREAD

**Issue by cat-stack-boop** [rmklaus12/all-about-git#21]
There's 3 pages, only 1 is needed. Make a pull request with only one contributor page included.

**Comment by vizpal** [comment]
Examined the 3 **contributor** pages in the repo.

**1.** **_contributors_page.html_ :** Active and linked to index.html but contents needs to be updated.
**2.** **_contributors.html_:**  Page contents needs updates.
**3.** **_contributor_page.html_:** Looks more like a contributors page with input fields for "Contributors Name", "Email" and "Bio".
    
If you agree with **3.**, I will go ahead and update the active link and remove **1.** and **2.** from the repo.

**Other Issues:** 
- Page requires updates to handle the inputs and the submit button.
- Irrelevant links in this page can be removed: "Home", "Topics"(x2),"Advanced Search"(x2), "Contributors"(x2), "Contributor_page"
- Style Sheet is also missing.

**Comment by vizpal** [comment]
I have not been able to assign this issue to myself... HELP!!

**Comment by vizpal** [comment]
@cat-stack-boop Please discuss before you make any updates to the suggestions above... Thanks

**Comment by rmklaus12** [comment]
@vizpal  we merged a change this morning to remove the 2nd and 3rd contributor page. Yes, there were forms on page 1 so we can create a new issue to design a page. Would you like to take that on?

**Comment by vizpal** [comment]
@rmklaus12 Yes... I can work on that...
Also, could we set some guidelines on working with issues and creating PR's..
I believe it would avoid confusion in the future.

**Comment by rmklaus12** [comment]
@vizpal - as this is a WIP, we definitely can and great suggestion!
