### ISSUE TITLE
A picture of a cat doing business 

### ISSUE THREAD

**Issue by cat-stack-boop** [rmklaus12/all-about-git#37]
# I would like a orange or light orange cat going about his daily cat business activities in a seperate page.

**Comment by rmklaus12** [comment]
@cat-stack-boop Thank you for raising this issue. Can you please explain to me the benefit this would bring to our website?

**Comment by cat-stack-boop** [comment]
@rmklaus12 it would bring an increase in cat lovers/aficionados who for have not been introduced to git before.
