### ISSUE TITLE
CSS styling not appearing on home page (index.html)

### ISSUE THREAD

**Issue by rmklaus12** [rmklaus12/all-about-git#8]
The styling is gone from the homepage. This needs to be resolved quickly!

**Comment by toxicfish** [comment]
I'll fix this

**Comment by vizpal** [comment]
I can see styling applied to index.html when viewed from chrome.
Is this issue fixed ?

**Comment by rmklaus12** [comment]
I’ll double check tomorrow!

**Comment by vizpal** [comment]
@rmklaus12 My Bad !! I was looking a fix that I was testing..
Anyways, have submitted a PR for what I had as the fix.
Please help review the PR.

**Comment by vizpal** [comment]
@rmklaus12 I see this as being merged with master.
I believe this can be closed.

**Comment by rmklaus12** [comment]
closing
